version: '3'
services:
  gpt-researcher:
    image: kramer1346/gpt-researcher
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
    restart: always
    ports:
      - 8000:8000
  # react-client:
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./gpt_researcher_nextjs
  #   volumes:
  #     - /app/node_modules
  #     - ./gpt_researcher_nextjs:/app
  #   restart: always
  #   ports:
  #     - 3000:3000